name: 'github-set-version'
description: 'Set IAC Module Version'
branding:
  icon: 'tag'
  color: 'gray-dark'
inputs:
  version:
    description: 'version# to set, will pull from environment variable version'
    required: false
  files:
    description: 'file patten to search for and replace version # in'
    required: true
  modules:
    description: 'file patten to search for and replace version # in'
    required: true
  debug:
    description: 'outputs instead of changing the file'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
